cc_test(
  name = "bytes",
  srcs = ["bytes_test.cpp"],
  deps = [
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "//lib/utils:utils",
  ],
)

cc_test(
  name = "unaligned_storage",
  srcs = ["unaligned_storage_test.cpp"],
  deps = [
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "//lib/utils:utils",
  ],
)
