cc_binary(
  name = "lzw_compress",
  srcs = ["src/lzw_compress.cpp"],
  deps = [
    "//lib/compression:compression",
    "//lib/utils:utils",
  ],
)

cc_binary(
  name = "lzw_decompress",
  srcs = ["src/lzw_decompress.cpp"],
  deps = [
    "//lib/compression:compression",
    "//lib/utils:utils",
  ],
)
